[package]
name = "versian"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.1.0"
bool_ext = "0.5.3"
enumflags2 = "0.7.6"
more-asserts = "0.3.1"
nom = "7.1.3"
pretty_assertions = "1.3.0"
rust-apt = { version = "0.5.1", optional = true }

[features]
cmp = ["rust-apt"]
